// Command docgen generates docs/commands.md from the bundled command
// registry (PRD 12.4: generated command documentation must match the
// registry). With -check it verifies the committed file is current instead
// of writing it, which gates documentation drift in CI (PRD SPEC-011).
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/rselbach/argmax/internal/spec"
)

const outPath = "docs/commands.md"

func main() {
	check := flag.Bool("check", false, "verify docs/commands.md is up to date instead of writing it")
	out := flag.String("out", outPath, "output file")
	flag.Parse()

	content := generate()

	if *check {
		existing, err := os.ReadFile(*out)
		if err != nil {
			fatalf("read %s: %v", *out, err)
		}
		if !bytes.Equal(existing, content) {
			fatalf("%s is out of date; regenerate with `go run ./tools/docgen`", *out)
		}
		fmt.Printf("%s is up to date\n", *out)
		return
	}

	if err := os.MkdirAll("docs", 0o755); err != nil {
		fatalf("mkdir docs: %v", err)
	}
	if err := os.WriteFile(*out, content, 0o644); err != nil {
		fatalf("write %s: %v", *out, err)
	}
	fmt.Printf("wrote %s\n", *out)
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "docgen: "+format+"\n", args...)
	os.Exit(1)
}

// generate renders the catalog documentation.
func generate() []byte {
	cats := spec.Categories()
	reg := spec.Default()

	entries := 0
	for _, c := range cats {
		entries += len(c.Specs)
	}

	var b strings.Builder
	b.WriteString("# argmax command catalog\n\n")
	b.WriteString("Generated by `tools/docgen` from the bundled registry. Do not edit by hand;\n")
	b.WriteString("regenerate with `go run ./tools/docgen` after changing the catalog.\n\n")
	fmt.Fprintf(&b, "%d category entries, %d distinct executable names, %d categories.\n",
		entries, len(reg.Names()), len(cats))

	for _, cat := range cats {
		specs := append([]*spec.Spec(nil), cat.Specs...)
		sort.Slice(specs, func(i, j int) bool { return specs[i].Name < specs[j].Name })
		fmt.Fprintf(&b, "\n## %s (%d)\n\n", cat.Name, len(cat.Specs))
		b.WriteString("| Command | Description | Subcommands | Options |\n")
		b.WriteString("| --- | --- | ---: | ---: |\n")
		for _, s := range specs {
			fmt.Fprintf(&b, "| `%s` | %s | %d | %d |\n",
				s.Name, cleanDesc(s.Description), countSubcommands(s), countOptions(s))
		}
	}
	return []byte(b.String())
}

// cleanDesc makes a description safe for a markdown table cell.
func cleanDesc(s string) string {
	return strings.ReplaceAll(strings.TrimSpace(s), "|", "\\|")
}

// countSubcommands counts the whole subcommand tree recursively.
func countSubcommands(s *spec.Spec) int {
	n := len(s.Subcommands)
	for _, sub := range s.Subcommands {
		n += countSubcommands(sub)
	}
	return n
}

// countOptions counts options recursively across the subcommand tree.
func countOptions(s *spec.Spec) int {
	n := len(s.Options)
	for _, sub := range s.Subcommands {
		n += countOptions(sub)
	}
	return n
}
