use super::{CatalogEntry, Category};

pub(super) const ENTRIES: &[CatalogEntry] = &[
    CatalogEntry::migrated(Category::CloudDevOps, "aws", "Amazon Web Services CLI"),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "aws-vault",
        "secure AWS credential manager",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "sam",
        "AWS serverless application CLI",
    ),
    CatalogEntry::migrated(Category::CloudDevOps, "cdk", "AWS cloud development kit"),
    CatalogEntry::migrated(Category::CloudDevOps, "istioctl", "Istio service mesh CLI"),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "eksctl",
        "Amazon EKS cluster manager",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "cilium",
        "Cilium networking and security CLI",
    ),
    CatalogEntry::migrated(Category::CloudDevOps, "eb", "AWS Elastic Beanstalk CLI"),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "session-manager-plugin",
        "AWS Session Manager client plugin",
    ),
    CatalogEntry::migrated(Category::CloudDevOps, "gcloud", "Google Cloud CLI"),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "gsutil",
        "Google Cloud Storage utility",
    ),
    CatalogEntry::migrated(Category::CloudDevOps, "bq", "Google BigQuery CLI"),
    CatalogEntry::migrated(Category::CloudDevOps, "firebase", "Firebase project CLI"),
    CatalogEntry::migrated(Category::CloudDevOps, "az", "Microsoft Azure CLI"),
    CatalogEntry::migrated(Category::CloudDevOps, "doctl", "DigitalOcean CLI"),
    CatalogEntry::migrated(Category::CloudDevOps, "heroku", "Heroku platform CLI"),
    CatalogEntry::migrated(Category::CloudDevOps, "flyctl", "Fly.io platform CLI"),
    CatalogEntry::migrated(Category::CloudDevOps, "vercel", "Vercel deployment CLI"),
    CatalogEntry::migrated(Category::CloudDevOps, "netlify", "Netlify deployment CLI"),
    CatalogEntry::migrated(Category::CloudDevOps, "railway", "Railway platform CLI"),
    CatalogEntry::migrated(Category::CloudDevOps, "wrangler", "Cloudflare Workers CLI"),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "cloudflared",
        "Cloudflare tunnel client",
    ),
    CatalogEntry::migrated(Category::CloudDevOps, "ibmcloud", "IBM Cloud CLI"),
    CatalogEntry::migrated(Category::CloudDevOps, "aliyun", "Alibaba Cloud CLI"),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "oci",
        "Oracle Cloud Infrastructure CLI",
    ),
    CatalogEntry::migrated(Category::CloudDevOps, "linode-cli", "Akamai Linode CLI"),
    CatalogEntry::migrated(Category::CloudDevOps, "hcloud", "Hetzner Cloud CLI"),
    CatalogEntry::migrated(Category::CloudDevOps, "scw", "Scaleway CLI"),
    CatalogEntry::migrated(Category::CloudDevOps, "exo", "Exoscale CLI"),
    CatalogEntry::migrated(Category::CloudDevOps, "civo", "Civo cloud CLI"),
    CatalogEntry::migrated(Category::CloudDevOps, "fastly", "Fastly edge cloud CLI"),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "pulumi",
        "infrastructure as code platform",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "terraform",
        "infrastructure as code CLI",
    ),
    CatalogEntry::migrated(Category::CloudDevOps, "tofu", "OpenTofu infrastructure CLI"),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "terragrunt",
        "Terraform orchestration wrapper",
    ),
    CatalogEntry::migrated(Category::CloudDevOps, "packer", "machine image builder"),
    CatalogEntry::migrated(Category::CloudDevOps, "vault", "secrets management CLI"),
    CatalogEntry::migrated(Category::CloudDevOps, "consul", "service discovery CLI"),
    CatalogEntry::migrated(Category::CloudDevOps, "nomad", "workload orchestration CLI"),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "boundary",
        "secure remote access CLI",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "dapr",
        "Dapr application runtime CLI",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "vagrant",
        "virtual development environment CLI",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "ansible",
        "configuration automation CLI",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "ansible-playbook",
        "Ansible playbook runner",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "ansible-galaxy",
        "Ansible content manager",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "ansible-vault",
        "Ansible secrets utility",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "molecule",
        "Ansible role test runner",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "puppet",
        "infrastructure automation CLI",
    ),
    CatalogEntry::migrated(Category::CloudDevOps, "chef", "Chef workstation CLI"),
    CatalogEntry::migrated(Category::CloudDevOps, "knife", "Chef infrastructure client"),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "inspec",
        "infrastructure compliance scanner",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "salt",
        "Salt remote execution client",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "salt-call",
        "Salt local execution client",
    ),
    CatalogEntry::migrated(Category::CloudDevOps, "juju", "model-driven operations CLI"),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "bosh",
        "BOSH deployment management CLI",
    ),
    CatalogEntry::migrated(Category::CloudDevOps, "cf", "Cloud Foundry CLI"),
    CatalogEntry::migrated(Category::CloudDevOps, "openstack", "OpenStack cloud CLI"),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "cinder",
        "OpenStack block storage client",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "swift",
        "OpenStack object storage client",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "barbican",
        "OpenStack key management client",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "docker",
        "container build and runtime CLI",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "kompose",
        "convert Compose applications to Kubernetes",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "podman",
        "daemonless container engine",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "podman-compose",
        "Podman Compose client",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "buildah",
        "Open Container Initiative image builder",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "skopeo",
        "container image inspection utility",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "nerdctl",
        "containerd command-line client",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "containerd",
        "container runtime daemon",
    ),
    CatalogEntry::migrated(Category::CloudDevOps, "ctr", "containerd debugging client"),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "crictl",
        "container runtime interface client",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "runc",
        "Open Container Initiative runtime",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "finch",
        "container development client",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "limactl",
        "Lima virtual machine manager",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "colima",
        "container runtime environment manager",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "minikube",
        "local Kubernetes cluster manager",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "kind",
        "Kubernetes-in-Docker cluster manager",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "k3d",
        "K3s-in-Docker cluster manager",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "k3s",
        "lightweight Kubernetes distribution",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "kubectl",
        "Kubernetes command-line client",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "kubeadm",
        "Kubernetes cluster bootstrapper",
    ),
    CatalogEntry::migrated(Category::CloudDevOps, "kubelet", "Kubernetes node agent"),
    CatalogEntry::migrated(Category::CloudDevOps, "helm", "Kubernetes package manager"),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "kustomize",
        "Kubernetes manifest customizer",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "kubectx",
        "Kubernetes context switcher",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "kubens",
        "Kubernetes namespace switcher",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "stern",
        "multi-pod Kubernetes log tailer",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "k9s",
        "Kubernetes terminal interface",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "helmfile",
        "declarative Helm release manager",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "kubeseal",
        "Sealed Secrets encryption client",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "argocd",
        "Argo CD command-line client",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "flux",
        "Flux continuous delivery CLI",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "tilt",
        "Kubernetes development environment",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "skaffold",
        "Kubernetes development workflow CLI",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "telepresence",
        "local-to-Kubernetes proxy",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "devspace",
        "Kubernetes development CLI",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "okteto",
        "Kubernetes development platform CLI",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "kubescape",
        "Kubernetes security scanner",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "trivy",
        "container vulnerability scanner",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "grype",
        "container vulnerability scanner",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "syft",
        "container software bill of materials tool",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "cosign",
        "container artifact signing client",
    ),
    CatalogEntry::migrated(Category::CloudDevOps, "crane", "container registry client"),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "oras",
        "OCI registry artifact client",
    ),
    CatalogEntry::migrated(Category::CloudDevOps, "regctl", "container registry client"),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "dive",
        "container image layer explorer",
    ),
    CatalogEntry::migrated(Category::CloudDevOps, "hadolint", "Dockerfile linter"),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "psql",
        "PostgreSQL interactive client",
    ),
    CatalogEntry::migrated(Category::CloudDevOps, "mysql", "MySQL interactive client"),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "mariadb",
        "MariaDB interactive client",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "sqlite3",
        "SQLite command-line shell",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "mongosh",
        "MongoDB interactive shell",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "redis-cli",
        "Redis command-line client",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "clickhouse-client",
        "ClickHouse command-line client",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "cockroach",
        "CockroachDB server and administration CLI",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "influx",
        "InfluxDB command-line client",
    ),
    CatalogEntry::migrated(
        Category::CloudDevOps,
        "cqlsh",
        "Apache Cassandra query shell",
    ),
    CatalogEntry::migrated(Category::CloudDevOps, "etcdctl", "etcd command-line client"),
    CatalogEntry::migrated(Category::CloudDevOps, "duckdb", "DuckDB command-line shell"),
    CatalogEntry::migrated(Category::Go, "go", "Go toolchain and module driver"),
    CatalogEntry::migrated(Category::Go, "gofmt", "Go source formatter"),
    CatalogEntry::migrated(Category::Go, "golangci-lint", "Go linters runner"),
    CatalogEntry::migrated(Category::Git, "git", "distributed version control system"),
    CatalogEntry::migrated(Category::Git, "gh", "GitHub command-line client"),
    CatalogEntry::migrated(Category::Git, "gitk", "Git repository history browser"),
    CatalogEntry::migrated(Category::Git, "git-lfs", "Git large file storage client"),
    CatalogEntry::migrated(Category::Git, "git-flow", "Git flow workflow extensions"),
    CatalogEntry::migrated(Category::Git, "glab", "GitLab command-line client"),
    CatalogEntry::migrated(Category::Git, "tig", "terminal Git repository browser"),
    CatalogEntry::migrated(Category::Git, "lazygit", "terminal Git client"),
];
