use super::{CatalogEntry, Category};

pub(super) const ENTRIES: &[CatalogEntry] = &[
    // C/C++ compilers and build systems (16).
    CatalogEntry::migrated(Category::Cpp, "gcc", "compile C and C++ programs with GCC"),
    CatalogEntry::migrated(Category::Cpp, "g++", "compile C++ programs with GCC"),
    CatalogEntry::migrated(
        Category::Cpp,
        "clang",
        "compile C-family programs with Clang",
    ),
    CatalogEntry::migrated(Category::Cpp, "clang++", "compile C++ programs with Clang"),
    CatalogEntry::migrated(Category::Cpp, "cc", "invoke the system C compiler"),
    CatalogEntry::migrated(Category::Cpp, "c++", "invoke the system C++ compiler"),
    CatalogEntry::migrated(
        Category::Cpp,
        "cmake",
        "configure and generate cross-platform builds",
    ),
    CatalogEntry::migrated(Category::Cpp, "ctest", "run tests from a CMake build tree"),
    CatalogEntry::migrated(
        Category::Cpp,
        "cpack",
        "create packages from CMake projects",
    ),
    CatalogEntry::migrated(Category::Cpp, "meson", "configure Meson build projects"),
    CatalogEntry::migrated(Category::Cpp, "ninja", "run Ninja builds"),
    CatalogEntry::migrated(Category::Cpp, "conan", "manage C and C++ dependencies"),
    CatalogEntry::migrated(Category::Cpp, "vcpkg", "manage cross-platform C++ packages"),
    CatalogEntry::migrated(
        Category::Cpp,
        "pkg-config",
        "query installed library metadata",
    ),
    CatalogEntry::migrated(Category::Cpp, "autoconf", "generate configure scripts"),
    CatalogEntry::migrated(
        Category::Cpp,
        "automake",
        "generate portable Makefile templates",
    ),
    // System package managers (12).
    CatalogEntry::migrated(Category::PackageManagers, "apt", "manage Debian packages"),
    CatalogEntry::migrated(
        Category::PackageManagers,
        "apt-get",
        "retrieve and install Debian packages",
    ),
    CatalogEntry::migrated(
        Category::PackageManagers,
        "apt-cache",
        "query Debian package metadata",
    ),
    CatalogEntry::migrated(
        Category::PackageManagers,
        "dpkg",
        "install and inspect Debian packages",
    ),
    CatalogEntry::migrated(
        Category::PackageManagers,
        "dnf",
        "manage RPM packages with DNF",
    ),
    CatalogEntry::migrated(
        Category::PackageManagers,
        "yum",
        "manage RPM packages with Yum",
    ),
    CatalogEntry::migrated(
        Category::PackageManagers,
        "rpm",
        "install and inspect RPM packages",
    ),
    CatalogEntry::migrated(
        Category::PackageManagers,
        "pacman",
        "manage Arch Linux packages",
    ),
    CatalogEntry::migrated(
        Category::PackageManagers,
        "zypper",
        "manage openSUSE packages",
    ),
    CatalogEntry::migrated(
        Category::PackageManagers,
        "brew",
        "manage Homebrew packages",
    ),
    CatalogEntry::migrated(
        Category::PackageManagers,
        "port",
        "manage MacPorts packages",
    ),
    CatalogEntry::migrated(
        Category::PackageManagers,
        "apk",
        "manage Alpine Linux packages",
    ),
    // Filesystem, directory, and archive utilities (30).
    CatalogEntry::migrated(Category::Filesystem, "ls", "list directory contents"),
    CatalogEntry::migrated(Category::Filesystem, "cp", "copy files and directories"),
    CatalogEntry::migrated(Category::Filesystem, "mv", "move or rename files"),
    CatalogEntry::migrated(Category::Filesystem, "rm", "remove files and directories"),
    CatalogEntry::migrated(Category::Filesystem, "mkdir", "create directories"),
    CatalogEntry::migrated(Category::Filesystem, "rmdir", "remove empty directories"),
    CatalogEntry::migrated(
        Category::Filesystem,
        "touch",
        "create files or update timestamps",
    ),
    CatalogEntry::migrated(Category::Filesystem, "ln", "create filesystem links"),
    CatalogEntry::migrated(
        Category::Filesystem,
        "readlink",
        "print a symbolic-link target",
    ),
    CatalogEntry::migrated(
        Category::Filesystem,
        "realpath",
        "resolve an absolute canonical path",
    ),
    CatalogEntry::migrated(Category::Filesystem, "pwd", "print the working directory"),
    CatalogEntry::migrated(
        Category::Filesystem,
        "basename",
        "strip directory components from a path",
    ),
    CatalogEntry::migrated(
        Category::Filesystem,
        "dirname",
        "strip the final component from a path",
    ),
    CatalogEntry::migrated(Category::Filesystem, "find", "search directory trees"),
    CatalogEntry::migrated(
        Category::Filesystem,
        "locate",
        "find paths in a filename database",
    ),
    CatalogEntry::migrated(
        Category::Filesystem,
        "tree",
        "display a directory hierarchy",
    ),
    CatalogEntry::migrated(
        Category::Filesystem,
        "du",
        "estimate file and directory usage",
    ),
    CatalogEntry::migrated(Category::Filesystem, "df", "report filesystem space usage"),
    CatalogEntry::migrated(
        Category::Filesystem,
        "stat",
        "show file or filesystem status",
    ),
    CatalogEntry::migrated(Category::Filesystem, "file", "identify file types"),
    CatalogEntry::migrated(Category::Filesystem, "truncate", "resize a file"),
    CatalogEntry::migrated(
        Category::Filesystem,
        "install",
        "copy files and set attributes",
    ),
    CatalogEntry::migrated(
        Category::Filesystem,
        "tar",
        "create and extract tar archives",
    ),
    CatalogEntry::migrated(Category::Filesystem, "gzip", "compress files with gzip"),
    CatalogEntry::migrated(Category::Filesystem, "gunzip", "decompress gzip files"),
    CatalogEntry::migrated(Category::Filesystem, "bzip2", "compress files with bzip2"),
    CatalogEntry::migrated(Category::Filesystem, "bunzip2", "decompress bzip2 files"),
    CatalogEntry::migrated(Category::Filesystem, "xz", "compress files with XZ"),
    CatalogEntry::migrated(Category::Filesystem, "zip", "create ZIP archives"),
    CatalogEntry::migrated(Category::Filesystem, "unzip", "extract ZIP archives"),
    // Editors, pagers, and file viewers (27).
    CatalogEntry::migrated(Category::Editors, "vi", "edit text with vi"),
    CatalogEntry::migrated(Category::Editors, "vim", "edit text with Vim"),
    CatalogEntry::migrated(Category::Editors, "nvim", "edit text with Neovim"),
    CatalogEntry::migrated(Category::Editors, "ex", "edit text with the ex line editor"),
    CatalogEntry::migrated(Category::Editors, "emacs", "edit text with Emacs"),
    CatalogEntry::migrated(Category::Editors, "nano", "edit text with Nano"),
    CatalogEntry::migrated(Category::Editors, "pico", "edit text with Pico"),
    CatalogEntry::migrated(
        Category::Editors,
        "ed",
        "edit text with the standard line editor",
    ),
    CatalogEntry::migrated(Category::Editors, "code", "open Visual Studio Code"),
    CatalogEntry::migrated(
        Category::Editors,
        "code-insiders",
        "open Visual Studio Code Insiders",
    ),
    CatalogEntry::migrated(Category::Editors, "subl", "open Sublime Text"),
    CatalogEntry::aliased(
        Category::Editors,
        "sublime_text",
        "open Sublime Text on Linux",
        "subl",
    ),
    CatalogEntry::migrated(Category::Editors, "atom", "open the Atom editor"),
    CatalogEntry::migrated(Category::Editors, "gedit", "open the GNOME text editor"),
    CatalogEntry::migrated(Category::Editors, "kate", "open the Kate editor"),
    CatalogEntry::migrated(Category::Editors, "kwrite", "open the KWrite editor"),
    CatalogEntry::migrated(Category::Editors, "mousepad", "open the Mousepad editor"),
    CatalogEntry::migrated(Category::Editors, "leafpad", "open the Leafpad editor"),
    CatalogEntry::migrated(Category::Editors, "geany", "open the Geany editor"),
    CatalogEntry::migrated(Category::Editors, "kak", "edit text with Kakoune"),
    CatalogEntry::migrated(Category::Editors, "hx", "open the Helix editor"),
    CatalogEntry::migrated(Category::Editors, "micro", "edit text with Micro"),
    CatalogEntry::migrated(Category::Editors, "joe", "edit text with Joe"),
    CatalogEntry::migrated(Category::Editors, "jed", "edit text with Jed"),
    CatalogEntry::migrated(Category::Editors, "less", "page through text interactively"),
    CatalogEntry::migrated(
        Category::Editors,
        "more",
        "page through text one screen at a time",
    ),
    CatalogEntry::migrated(
        Category::Editors,
        "bat",
        "view files with syntax highlighting",
    ),
    // Text processing, JSON, and stream manipulation (28).
    CatalogEntry::migrated(
        Category::Text,
        "cat",
        "concatenate files to standard output",
    ),
    CatalogEntry::migrated(
        Category::Text,
        "tac",
        "concatenate files in reverse line order",
    ),
    CatalogEntry::migrated(Category::Text, "head", "print the start of files"),
    CatalogEntry::migrated(Category::Text, "tail", "print the end of files"),
    CatalogEntry::migrated(Category::Text, "cut", "select fields from input lines"),
    CatalogEntry::migrated(Category::Text, "paste", "merge corresponding input lines"),
    CatalogEntry::migrated(Category::Text, "join", "join lines on a common field"),
    CatalogEntry::migrated(Category::Text, "sort", "sort lines of text"),
    CatalogEntry::migrated(
        Category::Text,
        "uniq",
        "report or remove adjacent duplicate lines",
    ),
    CatalogEntry::migrated(Category::Text, "tr", "translate or delete characters"),
    CatalogEntry::migrated(Category::Text, "wc", "count lines, words, and bytes"),
    CatalogEntry::migrated(Category::Text, "nl", "number input lines"),
    CatalogEntry::migrated(Category::Text, "fmt", "reformat text paragraphs"),
    CatalogEntry::migrated(Category::Text, "fold", "wrap input lines"),
    CatalogEntry::migrated(Category::Text, "column", "format input into columns"),
    CatalogEntry::migrated(Category::Text, "comm", "compare sorted files by line"),
    CatalogEntry::migrated(Category::Text, "cmp", "compare files byte by byte"),
    CatalogEntry::migrated(Category::Text, "diff", "compare files line by line"),
    CatalogEntry::migrated(Category::Text, "patch", "apply a diff to files"),
    CatalogEntry::migrated(Category::Text, "sed", "transform text streams"),
    CatalogEntry::migrated(Category::Text, "awk", "scan and process text records"),
    CatalogEntry::migrated(Category::Text, "grep", "search text by pattern"),
    CatalogEntry::aliased(
        Category::Text,
        "egrep",
        "search text with extended patterns",
        "grep",
    ),
    CatalogEntry::aliased(
        Category::Text,
        "fgrep",
        "search text for fixed strings",
        "grep",
    ),
    CatalogEntry::migrated(Category::Text, "jq", "query and transform JSON"),
    CatalogEntry::migrated(Category::Text, "yq", "query and transform YAML"),
    CatalogEntry::migrated(
        Category::Text,
        "xargs",
        "build commands from standard input",
    ),
    CatalogEntry::migrated(
        Category::Text,
        "tee",
        "copy input to files and standard output",
    ),
    // Task runners and build automation (24).
    CatalogEntry::migrated(Category::TaskRunners, "just", "run recipes from a justfile"),
    CatalogEntry::migrated(Category::TaskRunners, "make", "run Makefile build targets"),
    CatalogEntry::migrated(Category::TaskRunners, "gmake", "run GNU Make build targets"),
    CatalogEntry::migrated(Category::TaskRunners, "bmake", "run BSD Make build targets"),
    CatalogEntry::migrated(Category::TaskRunners, "task", "run tasks from a Taskfile"),
    CatalogEntry::migrated(Category::TaskRunners, "mage", "run Go-based build targets"),
    CatalogEntry::migrated(Category::TaskRunners, "invoke", "run Python Invoke tasks"),
    CatalogEntry::migrated(Category::TaskRunners, "doit", "run Python automation tasks"),
    CatalogEntry::migrated(Category::TaskRunners, "scons", "build software with SCons"),
    CatalogEntry::migrated(Category::TaskRunners, "waf", "configure and run Waf builds"),
    CatalogEntry::migrated(Category::TaskRunners, "buck", "run Buck builds"),
    CatalogEntry::migrated(Category::TaskRunners, "buck2", "run Buck2 builds"),
    CatalogEntry::migrated(Category::TaskRunners, "bazel", "run Bazel builds and tests"),
    CatalogEntry::migrated(Category::TaskRunners, "pants", "run Pants builds"),
    CatalogEntry::migrated(Category::TaskRunners, "plz", "run Please builds"),
    CatalogEntry::migrated(
        Category::TaskRunners,
        "earthly",
        "run reproducible container builds",
    ),
    CatalogEntry::migrated(
        Category::TaskRunners,
        "dagger",
        "run portable container pipelines",
    ),
    CatalogEntry::migrated(Category::TaskRunners, "turbo", "run Turborepo tasks"),
    CatalogEntry::migrated(Category::TaskRunners, "nx", "run Nx workspace tasks"),
    CatalogEntry::migrated(
        Category::TaskRunners,
        "lerna",
        "run tasks across JavaScript packages",
    ),
    CatalogEntry::migrated(Category::TaskRunners, "gulp", "run Gulp task pipelines"),
    CatalogEntry::migrated(Category::TaskRunners, "grunt", "run Grunt task pipelines"),
    CatalogEntry::migrated(
        Category::TaskRunners,
        "concurrently",
        "run commands concurrently",
    ),
    CatalogEntry::migrated(Category::TaskRunners, "rollup", "bundle JavaScript modules"),
];
