use super::{CatalogEntry, Category};

pub(super) const ENTRIES: &[CatalogEntry] = &[
    // System lifecycle, sessions, and service management.
    CatalogEntry::migrated(
        Category::System,
        "uname",
        "Report kernel and system identity",
    ),
    CatalogEntry::migrated(
        Category::System,
        "hostname",
        "Show or set the system host name",
    ),
    CatalogEntry::migrated(
        Category::System,
        "hostnamectl",
        "Manage the system host name and identity",
    ),
    CatalogEntry::migrated(Category::System, "uptime", "Show system uptime and load"),
    CatalogEntry::migrated(
        Category::System,
        "systemctl",
        "Control systemd units and services",
    ),
    CatalogEntry::migrated(Category::System, "service", "Control system services"),
    CatalogEntry::migrated(
        Category::System,
        "init",
        "Initialize the system or change its run state",
    ),
    CatalogEntry::migrated(Category::System, "telinit", "Change the system run level"),
    CatalogEntry::migrated(Category::System, "shutdown", "Schedule a system shutdown"),
    CatalogEntry::migrated(Category::System, "reboot", "Restart the system"),
    CatalogEntry::migrated(Category::System, "poweroff", "Power off the system"),
    CatalogEntry::migrated(Category::System, "halt", "Halt the system"),
    CatalogEntry::migrated(
        Category::System,
        "runlevel",
        "Show the current system run level",
    ),
    CatalogEntry::migrated(Category::System, "journalctl", "Query the systemd journal"),
    CatalogEntry::migrated(
        Category::System,
        "dmesg",
        "Inspect the kernel message buffer",
    ),
    CatalogEntry::migrated(
        Category::System,
        "sysctl",
        "Read and write kernel parameters",
    ),
    CatalogEntry::migrated(
        Category::System,
        "timedatectl",
        "Manage system time and time zones",
    ),
    CatalogEntry::migrated(
        Category::System,
        "localectl",
        "Manage system locale and keyboard settings",
    ),
    CatalogEntry::migrated(
        Category::System,
        "loginctl",
        "Inspect and manage login sessions",
    ),
    CatalogEntry::migrated(
        Category::System,
        "systemd-analyze",
        "Analyze systemd boot performance",
    ),
    CatalogEntry::migrated(
        Category::System,
        "systemd-run",
        "Run a command in a transient unit",
    ),
    CatalogEntry::migrated(
        Category::System,
        "systemd-cgls",
        "Show the systemd control-group tree",
    ),
    CatalogEntry::migrated(
        Category::System,
        "systemd-cgtop",
        "Monitor control-group resource use",
    ),
    CatalogEntry::migrated(
        Category::System,
        "coredumpctl",
        "Inspect saved process core dumps",
    ),
    CatalogEntry::migrated(
        Category::System,
        "busctl",
        "Inspect and control D-Bus services",
    ),
    CatalogEntry::migrated(
        Category::System,
        "machinectl",
        "Manage systemd machines and containers",
    ),
    CatalogEntry::migrated(
        Category::System,
        "launchctl",
        "Manage macOS launch services",
    ),
    CatalogEntry::migrated(
        Category::System,
        "scutil",
        "Manage macOS system configuration",
    ),
    CatalogEntry::migrated(Category::System, "pmset", "Manage macOS power settings"),
    CatalogEntry::migrated(
        Category::System,
        "sysdiagnose",
        "Collect macOS diagnostic information",
    ),
    // Process inspection, scheduling, and performance analysis.
    CatalogEntry::migrated(Category::System, "ps", "List running processes"),
    CatalogEntry::migrated(Category::System, "pstree", "Display processes as a tree"),
    CatalogEntry::migrated(
        Category::System,
        "pgrep",
        "Find processes by name or attributes",
    ),
    CatalogEntry::migrated(
        Category::System,
        "pkill",
        "Signal processes selected by attributes",
    ),
    CatalogEntry::migrated(Category::System, "kill", "Send a signal to a process"),
    CatalogEntry::migrated(Category::System, "killall", "Signal processes by name"),
    CatalogEntry::migrated(
        Category::System,
        "nice",
        "Run a process with adjusted priority",
    ),
    CatalogEntry::migrated(
        Category::System,
        "renice",
        "Adjust a running process priority",
    ),
    CatalogEntry::migrated(Category::System, "nohup", "Run a command immune to hangups"),
    CatalogEntry::migrated(Category::System, "setsid", "Run a program in a new session"),
    CatalogEntry::migrated(
        Category::System,
        "chrt",
        "Manage real-time process scheduling",
    ),
    CatalogEntry::migrated(Category::System, "taskset", "Set or inspect CPU affinity"),
    CatalogEntry::migrated(
        Category::System,
        "ionice",
        "Set process I/O scheduling priority",
    ),
    CatalogEntry::migrated(
        Category::System,
        "prlimit",
        "Inspect or change process resource limits",
    ),
    CatalogEntry::migrated(Category::System, "top", "Monitor processes and system load"),
    CatalogEntry::migrated(
        Category::System,
        "htop",
        "Interactively monitor system processes",
    ),
    CatalogEntry::migrated(
        Category::System,
        "btop",
        "Monitor system resources interactively",
    ),
    CatalogEntry::migrated(
        Category::System,
        "atop",
        "Record and inspect system activity",
    ),
    CatalogEntry::migrated(Category::System, "iotop", "Monitor process I/O activity"),
    CatalogEntry::migrated(
        Category::System,
        "powertop",
        "Analyze system power consumption",
    ),
    CatalogEntry::migrated(
        Category::System,
        "slabtop",
        "Monitor kernel slab cache usage",
    ),
    CatalogEntry::migrated(
        Category::System,
        "free",
        "Show physical and swap memory use",
    ),
    CatalogEntry::migrated(
        Category::System,
        "vmstat",
        "Report virtual-memory statistics",
    ),
    CatalogEntry::migrated(
        Category::System,
        "iostat",
        "Report CPU and device I/O statistics",
    ),
    CatalogEntry::migrated(
        Category::System,
        "mpstat",
        "Report per-processor statistics",
    ),
    CatalogEntry::migrated(
        Category::System,
        "pidstat",
        "Report statistics for selected processes",
    ),
    CatalogEntry::migrated(
        Category::System,
        "sar",
        "Collect and report system activity",
    ),
    CatalogEntry::migrated(
        Category::System,
        "numactl",
        "Control NUMA policy for processes",
    ),
    CatalogEntry::migrated(
        Category::System,
        "numastat",
        "Report NUMA memory statistics",
    ),
    CatalogEntry::migrated(
        Category::System,
        "lsof",
        "List open files and network sockets",
    ),
    CatalogEntry::migrated(
        Category::System,
        "fuser",
        "Identify processes using files or sockets",
    ),
    CatalogEntry::migrated(Category::System, "strace", "Trace process system calls"),
    CatalogEntry::migrated(Category::System, "ltrace", "Trace process library calls"),
    CatalogEntry::migrated(
        Category::System,
        "perf",
        "Profile Linux system and process events",
    ),
    CatalogEntry::migrated(
        Category::System,
        "watch",
        "Run a command periodically and show its output",
    ),
    CatalogEntry::migrated(Category::System, "pmap", "Report a process memory map"),
    CatalogEntry::migrated(
        Category::System,
        "pidof",
        "Find process identifiers by program name",
    ),
    CatalogEntry::migrated(Category::System, "tload", "Graph system load in a terminal"),
    CatalogEntry::migrated(
        Category::System,
        "smem",
        "Report proportional process memory use",
    ),
    CatalogEntry::migrated(
        Category::System,
        "dstat",
        "Report combined system resource statistics",
    ),
    // Accounts, privileges, authentication, and scheduled administration.
    CatalogEntry::migrated(Category::System, "who", "Show logged-in users"),
    CatalogEntry::migrated(
        Category::System,
        "w",
        "Show logged-in users and their activity",
    ),
    CatalogEntry::migrated(Category::System, "users", "List logged-in user names"),
    CatalogEntry::migrated(Category::System, "last", "Show recent login sessions"),
    CatalogEntry::migrated(
        Category::System,
        "lastlog",
        "Report the most recent user logins",
    ),
    CatalogEntry::migrated(Category::System, "id", "Show user and group identities"),
    CatalogEntry::migrated(Category::System, "groups", "Show group memberships"),
    CatalogEntry::migrated(Category::System, "getent", "Query system account databases"),
    CatalogEntry::migrated(Category::System, "passwd", "Change account passwords"),
    CatalogEntry::migrated(Category::System, "chpasswd", "Update passwords in batch"),
    CatalogEntry::migrated(Category::System, "useradd", "Create a user account"),
    CatalogEntry::migrated(Category::System, "usermod", "Modify a user account"),
    CatalogEntry::migrated(Category::System, "userdel", "Delete a user account"),
    CatalogEntry::migrated(Category::System, "groupadd", "Create a system group"),
    CatalogEntry::migrated(Category::System, "groupmod", "Modify a system group"),
    CatalogEntry::migrated(Category::System, "groupdel", "Delete a system group"),
    CatalogEntry::migrated(
        Category::System,
        "chage",
        "Manage password expiration policy",
    ),
    CatalogEntry::migrated(
        Category::System,
        "faillog",
        "Inspect or reset failed-login records",
    ),
    CatalogEntry::migrated(Category::System, "su", "Run a shell as another user"),
    CatalogEntry::migrated(
        Category::System,
        "sudo",
        "Execute a command with delegated privileges",
    ),
    CatalogEntry::migrated(Category::System, "visudo", "Safely edit sudo policy"),
    CatalogEntry::migrated(Category::System, "login", "Begin a user login session"),
    CatalogEntry::migrated(
        Category::System,
        "newgrp",
        "Switch the current group identity",
    ),
    CatalogEntry::migrated(
        Category::System,
        "sg",
        "Run a command with another group identity",
    ),
    CatalogEntry::migrated(
        Category::System,
        "setpriv",
        "Run a program with changed privileges",
    ),
    CatalogEntry::migrated(Category::System, "getcap", "Display file capabilities"),
    CatalogEntry::migrated(Category::System, "setcap", "Set file capabilities"),
    CatalogEntry::migrated(
        Category::System,
        "capsh",
        "Inspect and alter process capabilities",
    ),
    CatalogEntry::migrated(
        Category::System,
        "crontab",
        "Manage recurring command schedules",
    ),
    CatalogEntry::migrated(
        Category::System,
        "logrotate",
        "Rotate and retain system logs",
    ),
    // Network configuration, diagnosis, security, and remote access.
    CatalogEntry::migrated(
        Category::System,
        "ip",
        "Configure network interfaces and routes",
    ),
    CatalogEntry::migrated(Category::System, "ss", "Inspect network sockets"),
    CatalogEntry::migrated(
        Category::System,
        "ping",
        "Test network reachability with ICMP",
    ),
    CatalogEntry::migrated(
        Category::System,
        "ping6",
        "Test IPv6 reachability with ICMP",
    ),
    CatalogEntry::migrated(
        Category::System,
        "traceroute",
        "Trace network paths to a host",
    ),
    CatalogEntry::migrated(Category::System, "traceroute6", "Trace IPv6 network paths"),
    CatalogEntry::migrated(
        Category::System,
        "tracepath",
        "Discover a network path and MTU",
    ),
    CatalogEntry::migrated(
        Category::System,
        "mtr",
        "Continuously diagnose network paths",
    ),
    CatalogEntry::migrated(Category::System, "arp", "Inspect or change the ARP cache"),
    CatalogEntry::migrated(
        Category::System,
        "arping",
        "Probe neighbors with ARP requests",
    ),
    CatalogEntry::migrated(
        Category::System,
        "route",
        "Inspect or change the routing table",
    ),
    CatalogEntry::migrated(Category::System, "ifconfig", "Configure network interfaces"),
    CatalogEntry::migrated(
        Category::System,
        "netstat",
        "Display network status and connections",
    ),
    CatalogEntry::migrated(
        Category::System,
        "ethtool",
        "Inspect and configure Ethernet devices",
    ),
    CatalogEntry::migrated(Category::System, "iw", "Configure wireless network devices"),
    CatalogEntry::migrated(
        Category::System,
        "iwconfig",
        "Configure legacy wireless interfaces",
    ),
    CatalogEntry::migrated(
        Category::System,
        "nmcli",
        "Control NetworkManager from the terminal",
    ),
    CatalogEntry::migrated(
        Category::System,
        "nmtui",
        "Control NetworkManager interactively",
    ),
    CatalogEntry::migrated(
        Category::System,
        "resolvectl",
        "Inspect and configure DNS resolution",
    ),
    CatalogEntry::migrated(
        Category::System,
        "networkctl",
        "Inspect and configure network links",
    ),
    CatalogEntry::migrated(
        Category::System,
        "dhclient",
        "Acquire network settings with DHCP",
    ),
    CatalogEntry::migrated(Category::System, "udhcpc", "Run a lightweight DHCP client"),
    CatalogEntry::migrated(
        Category::System,
        "rfkill",
        "Enable or disable wireless transmitters",
    ),
    CatalogEntry::migrated(
        Category::System,
        "bridge",
        "Configure Ethernet bridge devices",
    ),
    CatalogEntry::migrated(Category::System, "tc", "Configure Linux traffic control"),
    CatalogEntry::migrated(Category::System, "nft", "Manage nftables firewall rules"),
    CatalogEntry::migrated(
        Category::System,
        "iptables",
        "Manage IPv4 packet-filter rules",
    ),
    CatalogEntry::migrated(
        Category::System,
        "ip6tables",
        "Manage IPv6 packet-filter rules",
    ),
    CatalogEntry::migrated(Category::System, "firewall-cmd", "Manage firewalld policy"),
    CatalogEntry::migrated(Category::System, "ufw", "Manage an uncomplicated firewall"),
    CatalogEntry::migrated(
        Category::System,
        "conntrack",
        "Inspect connection-tracking state",
    ),
    CatalogEntry::migrated(
        Category::System,
        "bpftool",
        "Inspect and manage BPF objects",
    ),
    CatalogEntry::migrated(
        Category::System,
        "tcpdump",
        "Capture and inspect network packets",
    ),
    CatalogEntry::migrated(
        Category::System,
        "tshark",
        "Analyze network packets in a terminal",
    ),
    CatalogEntry::migrated(Category::System, "nmap", "Scan hosts, ports, and services"),
    CatalogEntry::migrated(Category::System, "nc", "Read and write network connections"),
    CatalogEntry::migrated(
        Category::System,
        "ncat",
        "Relay data across network connections",
    ),
    CatalogEntry::migrated(
        Category::System,
        "socat",
        "Relay bidirectional data streams",
    ),
    CatalogEntry::migrated(Category::System, "telnet", "Connect to Telnet services"),
    CatalogEntry::migrated(Category::System, "ssh", "Open a secure remote shell"),
    CatalogEntry::migrated(Category::System, "ssh-keygen", "Create and manage SSH keys"),
    CatalogEntry::migrated(
        Category::System,
        "ssh-keyscan",
        "Collect public SSH host keys",
    ),
    CatalogEntry::migrated(Category::System, "ssh-add", "Load keys into an SSH agent"),
    CatalogEntry::migrated(
        Category::System,
        "ssh-agent",
        "Hold private keys for SSH clients",
    ),
    CatalogEntry::migrated(Category::System, "scp", "Copy files over SSH"),
    CatalogEntry::migrated(Category::System, "sftp", "Transfer files over SSH"),
    CatalogEntry::migrated(
        Category::System,
        "curl",
        "Transfer data with network protocols",
    ),
    CatalogEntry::migrated(
        Category::System,
        "wget",
        "Retrieve resources from the network",
    ),
    CatalogEntry::migrated(Category::System, "dig", "Query DNS servers"),
    CatalogEntry::migrated(Category::System, "host", "Look up DNS host information"),
    CatalogEntry::migrated(Category::System, "nslookup", "Query domain-name servers"),
    CatalogEntry::migrated(
        Category::System,
        "whois",
        "Query internet registration records",
    ),
    CatalogEntry::migrated(Category::System, "openvpn", "Create an OpenVPN tunnel"),
    CatalogEntry::migrated(Category::System, "wg", "Configure WireGuard interfaces"),
    CatalogEntry::migrated(
        Category::System,
        "wg-quick",
        "Bring up a WireGuard interface",
    ),
    // Kernel, hardware, IPC, namespaces, and audit controls.
    CatalogEntry::migrated(Category::System, "lsmod", "Show loaded kernel modules"),
    CatalogEntry::migrated(
        Category::System,
        "modprobe",
        "Load or remove kernel modules",
    ),
    CatalogEntry::migrated(Category::System, "insmod", "Insert a kernel module"),
    CatalogEntry::migrated(Category::System, "rmmod", "Remove a kernel module"),
    CatalogEntry::migrated(
        Category::System,
        "depmod",
        "Generate kernel module dependencies",
    ),
    CatalogEntry::migrated(
        Category::System,
        "udevadm",
        "Manage and inspect device events",
    ),
    CatalogEntry::migrated(
        Category::System,
        "dmidecode",
        "Decode system firmware hardware tables",
    ),
    CatalogEntry::migrated(Category::System, "lspci", "List PCI devices"),
    CatalogEntry::migrated(Category::System, "lsusb", "List USB devices"),
    CatalogEntry::migrated(
        Category::System,
        "lscpu",
        "Report CPU architecture information",
    ),
    CatalogEntry::migrated(
        Category::System,
        "lsipc",
        "List inter-process communication resources",
    ),
    CatalogEntry::migrated(Category::System, "ipcs", "Report System V IPC resources"),
    CatalogEntry::migrated(Category::System, "ipcmk", "Create System V IPC resources"),
    CatalogEntry::migrated(Category::System, "ipcrm", "Remove System V IPC resources"),
    CatalogEntry::migrated(
        Category::System,
        "nsenter",
        "Run a program in another process namespace",
    ),
    CatalogEntry::migrated(
        Category::System,
        "unshare",
        "Run a program in new namespaces",
    ),
    CatalogEntry::migrated(Category::System, "kexec", "Load and boot another kernel"),
    CatalogEntry::migrated(
        Category::System,
        "auditctl",
        "Configure the Linux audit system",
    ),
    CatalogEntry::migrated(Category::System, "ausearch", "Search Linux audit records"),
    CatalogEntry::migrated(Category::System, "sestatus", "Report SELinux policy status"),
];
