use super::{CatalogEntry, Category};

pub(super) const ENTRIES: &[CatalogEntry] = &[
    CatalogEntry::migrated(Category::JavaScript, "node", "Run JavaScript with Node.js"),
    CatalogEntry::migrated(Category::JavaScript, "npm", "Manage Node.js packages"),
    CatalogEntry::migrated(Category::JavaScript, "npx", "Run package-provided commands"),
    CatalogEntry::migrated(
        Category::JavaScript,
        "corepack",
        "Select package manager versions",
    ),
    CatalogEntry::migrated(Category::JavaScript, "yarn", "Manage JavaScript packages"),
    CatalogEntry::aliased(
        Category::JavaScript,
        "yarnpkg",
        "Invoke the Yarn package manager",
        "yarn",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "pnpm",
        "Manage content-addressed packages",
    ),
    CatalogEntry::migrated(Category::JavaScript, "pnpx", "Run pnpm package binaries"),
    CatalogEntry::migrated(Category::JavaScript, "bun", "Run the Bun toolkit"),
    CatalogEntry::migrated(Category::JavaScript, "bunx", "Run Bun package binaries"),
    CatalogEntry::migrated(
        Category::JavaScript,
        "deno",
        "Run secure JavaScript and TypeScript",
    ),
    CatalogEntry::migrated(Category::JavaScript, "tsc", "Compile TypeScript projects"),
    CatalogEntry::migrated(
        Category::JavaScript,
        "tsserver",
        "Serve TypeScript language features",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "ts-node",
        "Run TypeScript with Node.js",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "ts-node-dev",
        "Reload TypeScript Node.js programs",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "tsx",
        "Run TypeScript and ECMAScript modules",
    ),
    CatalogEntry::migrated(Category::JavaScript, "babel", "Transform JavaScript source"),
    CatalogEntry::migrated(
        Category::JavaScript,
        "babel-node",
        "Run Babel-transformed programs",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "webpack-cli",
        "Invoke the webpack command line",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "webpack-dev-server",
        "Serve webpack development builds",
    ),
    CatalogEntry::migrated(Category::JavaScript, "vite", "Build and serve web projects"),
    CatalogEntry::migrated(
        Category::JavaScript,
        "esbuild",
        "Bundle JavaScript and TypeScript",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "parcel",
        "Build zero-configuration web projects",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "browserify",
        "Bundle CommonJS modules",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "swc",
        "Compile JavaScript and TypeScript",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "rspack",
        "Bundle web applications with Rspack",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "microbundle",
        "Bundle small JavaScript libraries",
    ),
    CatalogEntry::migrated(Category::JavaScript, "next", "Build Next.js applications"),
    CatalogEntry::migrated(Category::JavaScript, "nuxt", "Build Nuxt applications"),
    CatalogEntry::migrated(Category::JavaScript, "nuxi", "Manage Nuxt projects"),
    CatalogEntry::migrated(Category::JavaScript, "astro", "Build Astro websites"),
    CatalogEntry::migrated(Category::JavaScript, "remix", "Develop Remix applications"),
    CatalogEntry::migrated(Category::JavaScript, "gatsby", "Build Gatsby sites"),
    CatalogEntry::migrated(
        Category::JavaScript,
        "eleventy",
        "Build Eleventy static sites",
    ),
    CatalogEntry::migrated(Category::JavaScript, "ng", "Manage Angular projects"),
    CatalogEntry::migrated(Category::JavaScript, "nest", "Manage NestJS applications"),
    CatalogEntry::migrated(Category::JavaScript, "vue", "Manage Vue projects"),
    CatalogEntry::migrated(
        Category::JavaScript,
        "vue-cli-service",
        "Run Vue CLI project tasks",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "create-react-app",
        "Create React applications",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "react-native",
        "Manage React Native applications",
    ),
    CatalogEntry::migrated(Category::JavaScript, "expo", "Develop Expo applications"),
    CatalogEntry::migrated(Category::JavaScript, "ionic", "Manage Ionic applications"),
    CatalogEntry::migrated(
        Category::JavaScript,
        "capacitor",
        "Manage Capacitor native projects",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "cordova",
        "Manage Cordova applications",
    ),
    CatalogEntry::migrated(Category::JavaScript, "quasar", "Manage Quasar applications"),
    CatalogEntry::migrated(
        Category::JavaScript,
        "svelte-check",
        "Check Svelte projects",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "storybook",
        "Develop component stories",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "styleguidist",
        "Develop React style guides",
    ),
    CatalogEntry::migrated(Category::JavaScript, "ember", "Manage Ember applications"),
    CatalogEntry::migrated(Category::JavaScript, "jest", "Run Jest tests"),
    CatalogEntry::migrated(Category::JavaScript, "vitest", "Run Vitest tests"),
    CatalogEntry::migrated(Category::JavaScript, "mocha", "Run Mocha tests"),
    CatalogEntry::migrated(Category::JavaScript, "ava", "Run AVA tests"),
    CatalogEntry::migrated(Category::JavaScript, "jasmine", "Run Jasmine tests"),
    CatalogEntry::migrated(
        Category::JavaScript,
        "karma",
        "Run browser tests with Karma",
    ),
    CatalogEntry::migrated(Category::JavaScript, "cypress", "Run Cypress browser tests"),
    CatalogEntry::migrated(
        Category::JavaScript,
        "playwright",
        "Run Playwright browser automation",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "puppeteer",
        "Manage Puppeteer browsers",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "eslint",
        "Lint JavaScript and TypeScript",
    ),
    CatalogEntry::migrated(Category::JavaScript, "prettier", "Format source files"),
    CatalogEntry::migrated(
        Category::JavaScript,
        "biome",
        "Lint and format web projects",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "standard",
        "Check JavaScript Standard Style",
    ),
    CatalogEntry::migrated(Category::JavaScript, "xo", "Lint JavaScript projects"),
    CatalogEntry::migrated(Category::JavaScript, "stylelint", "Lint stylesheets"),
    CatalogEntry::migrated(
        Category::JavaScript,
        "commitlint",
        "Validate commit messages",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "lint-staged",
        "Run checks on staged files",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "husky",
        "Manage Git hooks for projects",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "depcheck",
        "Find unused JavaScript dependencies",
    ),
    CatalogEntry::migrated(Category::JavaScript, "madge", "Analyze module dependencies"),
    CatalogEntry::migrated(
        Category::JavaScript,
        "jscodeshift",
        "Run JavaScript codemods",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "nodemon",
        "Restart Node.js programs on changes",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "forever",
        "Keep Node.js programs running",
    ),
    CatalogEntry::migrated(Category::JavaScript, "pm2", "Manage Node.js processes"),
    CatalogEntry::migrated(
        Category::JavaScript,
        "webpack",
        "Bundle JavaScript application assets",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "cross-env",
        "Set cross-platform environment variables",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "env-cmd",
        "Load environment variables for commands",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "dotenv",
        "Run commands with dotenv files",
    ),
    CatalogEntry::migrated(Category::JavaScript, "rimraf", "Remove files recursively"),
    CatalogEntry::migrated(Category::JavaScript, "shx", "Run portable shell utilities"),
    CatalogEntry::migrated(
        Category::JavaScript,
        "zx",
        "Write shell scripts in JavaScript",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "semantic-release",
        "Automate package releases",
    ),
    CatalogEntry::migrated(
        Category::JavaScript,
        "ncu",
        "Update package dependency declarations",
    ),
    CatalogEntry::migrated(Category::Python, "python", "Run the Python interpreter"),
    CatalogEntry::migrated(Category::Python, "python3", "Run the Python 3 interpreter"),
    CatalogEntry::migrated(Category::Python, "pip", "Install Python packages"),
    CatalogEntry::migrated(Category::Python, "pip3", "Install Python 3 packages"),
    CatalogEntry::migrated(
        Category::Python,
        "pipx",
        "Install isolated Python applications",
    ),
    CatalogEntry::migrated(
        Category::Python,
        "poetry",
        "Manage Python projects and dependencies",
    ),
    CatalogEntry::migrated(Category::Python, "pdm", "Manage modern Python projects"),
    CatalogEntry::migrated(Category::Python, "uv", "Manage fast Python environments"),
    CatalogEntry::migrated(
        Category::Python,
        "pipenv",
        "Manage Python virtual environments",
    ),
    CatalogEntry::migrated(Category::Python, "ruff", "Lint and format Python code"),
    CatalogEntry::migrated(Category::Python, "black", "Format Python code"),
    CatalogEntry::migrated(Category::Python, "isort", "Sort Python imports"),
    CatalogEntry::migrated(Category::Python, "flake8", "Check Python code style"),
    CatalogEntry::migrated(Category::Python, "mypy", "Check Python static types"),
    CatalogEntry::migrated(Category::Python, "pytest", "Run Python tests"),
    CatalogEntry::migrated(Category::Python, "tox", "Test Python environments"),
    CatalogEntry::migrated(Category::Python, "nox", "Automate Python test sessions"),
    CatalogEntry::migrated(Category::Python, "jupyter", "Run Jupyter tools"),
    CatalogEntry::migrated(Category::Python, "ipython", "Run interactive Python"),
    CatalogEntry::migrated(Category::Rust, "cargo", "Manage Rust projects"),
    CatalogEntry::migrated(Category::Rust, "rustc", "Compile Rust programs"),
    CatalogEntry::migrated(Category::Rust, "rustdoc", "Generate Rust documentation"),
    CatalogEntry::migrated(Category::Rust, "rustfmt", "Format Rust source code"),
    CatalogEntry::migrated(Category::Rust, "rustup", "Manage Rust toolchains"),
    CatalogEntry::migrated(
        Category::Rust,
        "rust-analyzer",
        "Serve Rust language features",
    ),
    CatalogEntry::migrated(Category::Rust, "clippy-driver", "Run Rust lint analysis"),
    CatalogEntry::migrated(
        Category::Rust,
        "cargo-miri",
        "Run Rust code and tests under Miri",
    ),
    CatalogEntry::migrated(Category::Rust, "rust-gdb", "Debug Rust programs with GDB"),
    CatalogEntry::migrated(Category::Rust, "rust-lldb", "Debug Rust programs with LLDB"),
    CatalogEntry::migrated(Category::Rust, "mdbook", "Build books from Markdown"),
    CatalogEntry::migrated(Category::Jvm, "java", "Run Java applications"),
    CatalogEntry::migrated(Category::Jvm, "javac", "Compile Java source code"),
    CatalogEntry::migrated(Category::Jvm, "javadoc", "Generate Java API documentation"),
    CatalogEntry::migrated(Category::Jvm, "javap", "Inspect Java class files"),
    CatalogEntry::migrated(Category::Jvm, "jshell", "Run the Java interactive shell"),
    CatalogEntry::migrated(Category::Jvm, "jlink", "Build custom Java runtimes"),
    CatalogEntry::migrated(Category::Jvm, "jmod", "Manage Java module files"),
    CatalogEntry::migrated(Category::Jvm, "jdeps", "Analyze Java dependencies"),
    CatalogEntry::migrated(Category::Jvm, "jpackage", "Package Java applications"),
    CatalogEntry::migrated(Category::Jvm, "mvn", "Build Maven projects"),
    CatalogEntry::migrated(Category::Jvm, "gradle", "Build Gradle projects"),
    CatalogEntry::migrated(Category::Jvm, "kotlinc", "Compile Kotlin source code"),
    CatalogEntry::migrated(Category::Jvm, "scala", "Run Scala programs"),
    CatalogEntry::migrated(Category::Jvm, "sbt", "Build Scala projects"),
];
