package catalog

import (
	"fmt"
	"strings"
)

// GenerateDocs renders the catalog documentation from the live registry
// and manifest. tools/docgen writes it to docs/commands.md and CI fails
// when the committed file drifts from the registry.
func GenerateDocs() (string, error) {
	m, err := LoadManifest()
	if err != nil {
		return "", err
	}
	reg := Registry()
	var b strings.Builder
	b.WriteString("# argmax command catalog\n\n")
	b.WriteString("Generated by `tools/docgen` from the bundled registry. Do not edit by hand;\n")
	b.WriteString("regenerate with `go run ./tools/docgen` after changing the catalog.\n")
	total, distinct := 0, map[string]bool{}
	for _, cat := range m.Categories {
		total += len(cat.Entries)
		for _, e := range cat.Entries {
			distinct[e] = true
		}
	}
	fmt.Fprintf(&b, "\n%d category entries, %d distinct executable names, %d categories.\n", total, len(distinct), len(m.Categories))
	for _, cat := range m.Categories {
		fmt.Fprintf(&b, "\n## %s (%d)\n\n", cat.Title, len(cat.Entries))
		b.WriteString("| Command | Description | Subcommands | Options |\n")
		b.WriteString("| --- | --- | ---: | ---: |\n")
		for _, name := range cat.Entries {
			spec := reg.Lookup(name)
			if spec == nil {
				return "", fmt.Errorf("catalog entry %q does not resolve in the registry", name)
			}
			desc := strings.ReplaceAll(spec.Description, "|", "\\|")
			fmt.Fprintf(&b, "| `%s` | %s | %d | %d |\n", name, desc, len(spec.Subcommands), len(spec.Options))
		}
	}
	return b.String(), nil
}
