package catalog

import (
	"fmt"
	"strings"

	"github.com/rselbach/argmax/internal/complete"
	"github.com/rselbach/argmax/internal/generators"
)

// SpecData is the on-disk JSON form of one command specification. Data
// files under data/ are generated by tools/cataloggen and embedded into
// the binary; the schema mirrors complete.Spec with generators expressed
// as named references.
type SpecData struct {
	Name        string       `json:"name"`
	Aliases     []string     `json:"aliases,omitempty"`
	Description string       `json:"description,omitempty"`
	Icon        string       `json:"icon,omitempty"`
	Priority    int          `json:"priority,omitempty"`
	MaxArgs     int          `json:"maxArgs,omitempty"`
	Generator   string       `json:"generator,omitempty"`
	Values      []ValueData  `json:"values,omitempty"`
	Options     []OptionData `json:"options,omitempty"`
	Subcommands []*SpecData  `json:"subcommands,omitempty"`
}

// ValueData is one static positional value suggestion.
type ValueData struct {
	Name        string `json:"name"`
	Description string `json:"description,omitempty"`
}

// OptionData is the on-disk form of one option.
type OptionData struct {
	Names       []string `json:"names"`
	Description string   `json:"description,omitempty"`
	TakesArg    bool     `json:"takesArg,omitempty"`
	// Generator names the value source for the option's argument.
	Generator string `json:"generator,omitempty"`
}

// Manifest records the PRD catalog contract: every category with its
// required entry names. Entries may resolve to either a Go-coded or a
// data-driven spec.
type Manifest struct {
	Categories []ManifestCategory `json:"categories"`
}

// ManifestCategory is one PRD section 18 category.
type ManifestCategory struct {
	Title   string   `json:"title"`
	Slug    string   `json:"slug"`
	Icon    string   `json:"icon"`
	Entries []string `json:"entries"`
}

// ToSpec converts the data form into a runtime spec, resolving generator
// references and static values.
func (d *SpecData) ToSpec() (*complete.Spec, error) {
	s := &complete.Spec{
		Name:        d.Name,
		Aliases:     d.Aliases,
		Description: d.Description,
		Icon:        d.Icon,
		Priority:    d.Priority,
		MaxArgs:     d.MaxArgs,
	}
	gen, err := ResolveGenerator(d.Generator)
	if err != nil {
		return nil, fmt.Errorf("spec %s: %w", d.Name, err)
	}
	if len(d.Values) > 0 {
		gen = combineGenerators(staticValues(d.Values), gen)
	}
	s.Generator = gen
	for _, o := range d.Options {
		optGen, err := ResolveGenerator(o.Generator)
		if err != nil {
			return nil, fmt.Errorf("spec %s option %v: %w", d.Name, o.Names, err)
		}
		s.Options = append(s.Options, complete.Option{
			Names:       o.Names,
			Description: o.Description,
			TakesArg:    o.TakesArg,
			Generator:   optGen,
		})
	}
	for _, sub := range d.Subcommands {
		converted, err := sub.ToSpec()
		if err != nil {
			return nil, err
		}
		s.Subcommands = append(s.Subcommands, converted)
	}
	return s, nil
}

// GeneratorNames lists the named generators data specs may reference.
// Parameterized forms: "files:ext1,ext2" and "installed-packages:<mgr>".
var generatorFactories = map[string]func(arg string) complete.Generator{
	"files": func(arg string) complete.Generator {
		if arg == "" {
			return generators.Files()
		}
		return generators.FilesWithExt(strings.Split(arg, ",")...)
	},
	"directories":          func(string) complete.Generator { return generators.Directories() },
	"git-branches":         func(string) complete.Generator { return generators.GitBranches() },
	"git-checkout-targets": func(string) complete.Generator { return generators.GitCheckoutTargets() },
	"git-refs":             func(string) complete.Generator { return generators.GitRefs() },
	"git-push-pull":        func(string) complete.Generator { return generators.GitPushPull() },
	"git-reset-targets":    func(string) complete.Generator { return generators.GitResetTargets() },
	"git-show-targets":     func(string) complete.Generator { return generators.GitShowTargets() },
	"docker-containers":    func(string) complete.Generator { return generators.DockerContainers(false) },
	"docker-running":       func(string) complete.Generator { return generators.DockerContainers(true) },
	"docker-images":        func(string) complete.Generator { return generators.DockerImages() },
	"docker-inspect":       func(string) complete.Generator { return generators.DockerInspectTargets() },
	"ssh-hosts":            func(string) complete.Generator { return generators.SSHHosts() },
	"env-vars":             func(string) complete.Generator { return generators.EnvVars() },
	"processes":            func(string) complete.Generator { return generators.Processes() },
	"chmod-modes":          func(string) complete.Generator { return generators.ChmodModes() },
	"zoxide":               func(string) complete.Generator { return generators.Zoxide() },
	"package-scripts":      func(string) complete.Generator { return generators.PackageScripts() },
	"just-recipes":         func(string) complete.Generator { return generators.JustRecipes() },
	"make-targets":         func(string) complete.Generator { return generators.MakeTargets() },
	"pip-packages":         func(string) complete.Generator { return generators.PipPackages() },
	"installed-packages":   generators.InstalledPackages,
}

// ResolveGenerator maps a generator reference such as "files",
// "files:go,mod", or "ssh-hosts" to its implementation. An empty name
// yields nil; an unknown name is an error so CI catches drift.
func ResolveGenerator(name string) (complete.Generator, error) {
	if name == "" {
		return nil, nil
	}
	base, arg, _ := strings.Cut(name, ":")
	factory, ok := generatorFactories[base]
	if !ok {
		return nil, fmt.Errorf("unknown generator reference %q", name)
	}
	return factory(arg), nil
}

// staticValues builds a generator serving fixed positional suggestions.
func staticValues(values []ValueData) complete.Generator {
	return func(_ complete.Context, _ []string, prefix string) []complete.Candidate {
		var out []complete.Candidate
		for _, v := range values {
			if len(v.Name) < len(prefix) || !strings.EqualFold(v.Name[:len(prefix)], prefix) {
				continue
			}
			out = append(out, complete.Candidate{
				Title:       v.Name,
				Description: v.Description,
				Priority:    40,
			})
		}
		return out
	}
}

func combineGenerators(gens ...complete.Generator) complete.Generator {
	var active []complete.Generator
	for _, g := range gens {
		if g != nil {
			active = append(active, g)
		}
	}
	if len(active) == 0 {
		return nil
	}
	if len(active) == 1 {
		return active[0]
	}
	return func(ctx complete.Context, args []string, prefix string) []complete.Candidate {
		var out []complete.Candidate
		for _, g := range active {
			out = append(out, g(ctx, args, prefix)...)
		}
		return out
	}
}

// GoSpecNames returns the names (and aliases) implemented as Go code;
// tools/cataloggen skips these so hand-tuned specs keep precedence.
func GoSpecNames() []string {
	var names []string
	for _, s := range specs() {
		names = append(names, s.Name)
		names = append(names, s.Aliases...)
	}
	return names
}
