package spec

// taskCount is the PRD 18.13 category size (task runners and build
// automation).
const taskCount = 24

func catalogTask() []*Spec {
	return []*Spec{
		{
			Name:        "ant",
			Description: "Apache Ant build tool",
			Icon:        "build",
			Options: []Option{
				optGen("files", "Build file", "-f", "-file", "-buildfile"),
				optD("Print the project help", "-p", "-projecthelp"),
				optVal("Set a property", "-D"),
			},
		},
		{
			Name:        "composer",
			Description: "PHP dependency manager",
			Icon:        "package",
			Subcommands: []*Spec{
				cmd("install", "Install dependencies", "package"),
				cmd("require", "Add a dependency", "package"),
				cmd("remove", "Remove a dependency", "package"),
				cmd("update", "Update dependencies", "package"),
				cmd("dump-autoload", "Regenerate the autoloader", "package"),
				cmd("create-project", "Create a project from a package", "package"),
				cmd("show", "Show package details", "package"),
				cmd("outdated", "Check for outdated packages", "package"),
			},
		},
		{
			Name:        "dbt",
			Description: "Data build tool",
			Icon:        "database",
			Subcommands: []*Spec{
				cmd("run", "Run models", "database"),
				cmd("test", "Run tests", "database"),
				cmd("build", "Build models and run tests", "database"),
				cmd("compile", "Compile models", "database"),
				cmd("docs", "Manage documentation", "database"),
				cmd("debug", "Debug the connection", "database"),
				cmd("deps", "Install dependencies", "database"),
				cmd("seed", "Load seed files", "database"),
				cmd("snapshot", "Run snapshots", "database"),
			},
		},
		{
			Name:        "drush",
			Description: "Drupal shell",
			Icon:        "task",
			Subcommands: []*Spec{
				cmd("cr", "Rebuild the cache", "task"),
				cmd("status", "Show the site status", "task"),
				cmd("updb", "Apply database updates", "task"),
				cmd("cex", "Export configuration", "task"),
				cmd("cim", "Import configuration", "task"),
				cmd("sql-cli", "Open a database shell", "task"),
			},
		},
		{
			Name:        "elixir",
			Description: "Elixir language runtime",
			Icon:        "misc",
			Options: []Option{
				optVal("Evaluate an expression", "-e"),
				optD("Show version", "-v", "--version"),
				optGen("files", "Require a file", "-r"),
			},
		},
		{
			Name:        "gem",
			Description: "RubyGems package manager",
			Icon:        "package",
			Subcommands: []*Spec{
				cmd("install", "Install a gem", "package"),
				cmd("uninstall", "Uninstall a gem", "package"),
				cmd("list", "List installed gems", "package"),
				cmd("search", "Search for gems", "package"),
				cmd("update", "Update gems", "package"),
				cmd("push", "Publish a gem", "package"),
				cmd("build", "Build a gem", "package"),
			},
		},
		{
			Name:        "hexo",
			Description: "Static site generator",
			Icon:        "build",
			Subcommands: []*Spec{
				cmd("new", "Create a new post", "build"),
				cmd("generate", "Generate the static files", "build"),
				cmd("server", "Start the dev server", "build"),
				cmd("deploy", "Deploy the site", "build"),
				cmd("clean", "Clean the cache", "build"),
			},
		},
		{
			Name:        "just",
			Description: "Command runner",
			Icon:        "task",
			Options: []Option{
				optGen("files", "Use a specific justfile", "-f", "--justfile"),
				optD("List available recipes", "-l", "--list"),
				optVal("Show a recipe", "--show"),
				optGen("dirs", "Set the working directory", "-d", "--working-directory"),
			},
			Generator: "just-recipes",
		},
		{
			Name:        "laravel",
			Description: "Laravel installer",
			Icon:        "misc",
			Subcommands: []*Spec{
				cmd("new", "Create a new Laravel application", "misc"),
			},
		},
		{
			Name:        "magento",
			Description: "Magento CLI",
			Icon:        "misc",
			Subcommands: []*Spec{
				cmd("setup:upgrade", "Upgrade the database schema", "misc"),
				cmd("cache:flush", "Flush the cache", "misc"),
				cmd("cache:clean", "Clean the cache", "misc"),
				cmd("indexer:reindex", "Reindex the indexers", "misc"),
			},
		},
		{
			Name:        "make",
			Description: "Build automation tool",
			Icon:        "task",
			Options: []Option{
				optGen("files", "Use a specific makefile", "-f", "--file"),
				optVal("Run n jobs in parallel", "-j", "--jobs"),
				optGen("dirs", "Change to directory first", "-C", "--directory"),
				optD("Print what would be done", "-n", "--dry-run"),
				optD("Rebuild everything", "-B", "--always-make"),
				optD("Silent operation", "-s", "--silent"),
			},
			Generator: "make-targets",
		},
		{
			Name:        "mix",
			Description: "Elixir build tool",
			Icon:        "misc",
			Subcommands: []*Spec{
				cmd("compile", "Compile the project", "misc"),
				cmd("test", "Run the tests", "misc"),
				cmd("format", "Format the code", "misc"),
				cmd("new", "Create a project", "misc"),
				cmd("deps.get", "Fetch dependencies", "misc"),
				cmd("deps.update", "Update a dependency", "misc"),
				cmd("ecto.create", "Create the database", "misc"),
				cmd("ecto.migrate", "Run migrations", "misc"),
				cmd("phx.server", "Start the Phoenix server", "misc"),
			},
		},
		{
			Name:        "php",
			Description: "PHP interpreter",
			Icon:        "misc",
			Options: []Option{
				optD("Show version", "-v", "--version"),
				optGen("files", "Parse and execute a file", "-f"),
				optVal("Run code directly", "-r"),
				optVal("Start the built-in web server", "-S"),
				optD("List compiled modules", "-m"),
			},
			Generator: "ext:php",
		},
		{
			Name:        "phpunit",
			Description: "PHP testing framework",
			Icon:        "misc",
			Options: []Option{
				optVal("Filter tests by name", "--filter"),
				optVal("Run a test suite", "--testsuite"),
				optD("Show coverage as text", "--coverage-text"),
			},
			Generator: "ext:php",
		},
		genCmd("phpunit-watcher", "Re-run PHPUnit on file changes", "misc", "ext:php"),
		{
			Name:        "rails",
			Description: "Ruby on Rails",
			Icon:        "misc",
			Subcommands: []*Spec{
				{Name: "server", Aliases: []string{"s"}, Description: "Start the server", Icon: "misc"},
				{Name: "console", Aliases: []string{"c"}, Description: "Start the console", Icon: "misc"},
				{Name: "generate", Aliases: []string{"g"}, Description: "Generate code", Icon: "misc"},
				cmd("new", "Create an application", "misc"),
				cmd("db:migrate", "Run database migrations", "misc"),
				cmd("routes", "List routes", "misc"),
				cmd("test", "Run tests", "misc"),
			},
		},
		{
			Name:        "rake",
			Description: "Ruby make",
			Icon:        "task",
			Options: []Option{
				optGen("files", "Use a specific rakefile", "-f", "--rakefile"),
				optD("List the tasks", "-T", "--tasks"),
				optD("Dry run", "-n", "--dry-run"),
			},
		},
		{
			Name:        "rubocop",
			Description: "Ruby linter and formatter",
			Icon:        "misc",
			Options: []Option{
				optD("Autocorrect all offenses", "-A"),
				optD("Autocorrect safe offenses", "-a"),
				optVal("Run only specific cops", "--only"),
			},
		},
		{
			Name:        "ruby",
			Description: "Ruby interpreter",
			Icon:        "misc",
			Options: []Option{
				optVal("Execute a command", "-e"),
				optD("Show version", "-v"),
				optD("Enable warnings", "-w"),
				optVal("Add a load path", "-I"),
			},
			Generator: "files",
		},
		{
			Name:        "rvm",
			Description: "Ruby version manager",
			Icon:        "package",
			Subcommands: []*Spec{
				cmd("install", "Install a Ruby version", "package"),
				cmd("use", "Switch to a Ruby version", "package"),
				cmd("list", "List installed versions", "package"),
				cmd("gemset", "Manage gemsets", "package"),
				cmd("current", "Show the current version", "package"),
			},
		},
		{
			Name:        "sidekiq",
			Description: "Background job processor for Ruby",
			Icon:        "misc",
			Options: []Option{
				optVal("Process a queue", "-q"),
				optVal("Concurrency", "-c"),
				optVal("Environment", "-e"),
			},
		},
		{
			Name:        "symfony",
			Description: "Symfony CLI",
			Icon:        "misc",
			Subcommands: []*Spec{
				cmd("new", "Create a new project", "misc"),
				cmd("serve", "Start the local web server", "misc"),
				cmd("server:start", "Start the local web server", "misc"),
				cmd("server:stop", "Stop the local web server", "misc"),
				cmd("console", "Run console commands", "misc"),
			},
		},
		{
			Name:        "valet",
			Description: "Laravel Valet development environment",
			Icon:        "misc",
			Subcommands: []*Spec{
				cmd("install", "Install Valet", "misc"),
				cmd("uninstall", "Uninstall Valet", "misc"),
				cmd("park", "Register a directory", "misc"),
				cmd("link", "Link a site", "misc"),
				cmd("unlink", "Unlink a site", "misc"),
				cmd("start", "Start Valet", "misc"),
				cmd("stop", "Stop Valet", "misc"),
				cmd("restart", "Restart Valet", "misc"),
			},
		},
		{
			Name:        "vapor",
			Description: "Vapor Swift framework CLI",
			Icon:        "misc",
			Subcommands: []*Spec{
				cmd("new", "Create a project", "misc"),
				cmd("build", "Build the project", "misc"),
				cmd("run", "Run the project", "misc"),
				cmd("deploy", "Deploy the project", "misc"),
			},
		},
	}
}
